### ISSUE TITLE
inflation layers crashs when robot pose had a big change

### ISSUE THREAD

**Issue by randoms** [ros-planning/navigation#1155]
distanceLookup keeps a cache of distance by cached_distances_, but when robot pose had a big change, index dx, dy would out of range

https://github.com/ros-planning/navigation/blob/2b807bd312fac1b476851800c84cb962559cbc53/costmap_2d/include/costmap_2d/inflation_layer.h#L147-L152

**Comment by randoms** [comment]
gdb info

```
Core was generated by `/home/xiaoqiang/Documents/ros/devel/lib/move_base/move_base /odom:=/xqserial_se'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa99c2f0c59 in costmap_2d::InflationLayer::distanceLookup (
    this=0x559a2c90d490, src_y=114, src_x=162, my=114, mx=138)
    at /home/xiaoqiang/Documents/ros/src/navigation/costmap_2d/include/costmap_2d/inflation_layer.h:151
151	    return cached_distances_[dx][dy];
[Current thread is 1 (Thread 0x7fa994ff9700 (LWP 1512495))]
(gdb) bt
#0  0x00007fa99c2f0c59 in costmap_2d::InflationLayer::distanceLookup (
    this=0x559a2c90d490, src_y=114, src_x=162, my=114, mx=138)
    at /home/xiaoqiang/Documents/ros/src/navigation/costmap_2d/include/costmap_2d/inflation_layer.h:151
#1  costmap_2d::InflationLayer::enqueue (this=this@entry=0x559a2c90d490, 
    index=index@entry=27498, mx=mx@entry=138, my=my@entry=114, 
    src_x=src_x@entry=162, src_y=src_y@entry=114)
    at /home/xiaoqiang/Documents/ros/src/navigation/costmap_2d/plugins/inflation_layer.cpp:302
#2  0x00007fa99c2f120f in costmap_2d::InflationLayer::enqueue (src_y=114, 
    src_x=162, my=114, mx=138, index=27498, this=0x559a2c90d490)
    at /home/xiaoqiang/Documents/ros/src/navigation/costmap_2d/plugins/inflation_layer.cpp:297
#3  costmap_2d::InflationLayer::updateCosts (this=0x559a2c90d490, master_grid=
    ..., min_i=0, min_j=<optimized out>, max_i=<optimized out>, 
    max_j=<optimized out>)
    at /home/xiaoqiang/Documents/ros/src/navigation/costmap_2d/plugins/inflation_layer.cpp:272
#4  0x00007fa9a131505d in costmap_2d::LayeredCostmap::updateMap (
    this=0x559a2c8fea60, robot_x=robot_x@entry=0.83699568278117653, 
    robot_y=robot_y@entry=-7.739114290440039, 
    robot_yaw=robot_yaw@entry=-1.4358852918336098)
```

It seems the index was OK, but memory  was corrupted.
